# Generated by Django 4.0.2 on 2022-04-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='is_big_plan',
            field=models.BooleanField(default=False, verbose_name='Design if the plan is available'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(default='42593772', unique=True, verbose_name=''),
        ),
    ]
