# Generated by Django 4.1.5 on 2023-01-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_match_match_id_alter_videoproof_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(default='84886534', verbose_name='Match Id'),
        ),
    ]
