# Generated by Django 4.0.2 on 2022-04-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_encryptedproof_key_alter_match_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(default='62650216', unique=True, verbose_name='Match Id'),
        ),
    ]
