# Generated by Django 4.1.5 on 2023-01-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_match_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(default='60047808', verbose_name='Match Id'),
        ),
    ]
