# Generated by Django 4.0.2 on 2022-04-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_match_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedproof',
            name='display_key',
            field=models.BooleanField(default=True, verbose_name='Display the key'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(default='34875228', unique=True, verbose_name='Match Id'),
        ),
    ]
