# Generated by Django 4.1.5 on 2023-01-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_match_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(default='40328867', verbose_name='Match Id'),
        ),
        migrations.AlterField(
            model_name='videoproof',
            name='resume',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Resumé'),
        ),
    ]
