# Generated by Django 4.0.2 on 2022-05-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_encryptedproof_display_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(default='58215882', unique=True, verbose_name='Match Id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='odd_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('ht_ft', 'Half / Full Time'), ('full_time', 'Full Time')], max_length=220, verbose_name='Odds type'),
        ),
        migrations.AlterField(
            model_name='match',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Price'),
        ),
    ]
