# Generated by Django 4.1.5 on 2023-02-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_match_match_id_alter_videoproof_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(default='88107935', verbose_name='Match Id'),
        ),
        migrations.AlterField(
            model_name='videoproof',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videosprofs/thumbnails', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='videoproof',
            name='video',
            field=models.FileField(upload_to='videosprofs/files', verbose_name='Fichier Vidéo'),
        ),
    ]
