# Generated by Django 4.0.2 on 2022-05-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_match_match_id_alter_match_odd_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(default='09009939', unique=True, verbose_name='Match Id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price'),
        ),
    ]
