# Generated by Django 4.0.6 on 2022-07-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_match_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(default='93892793', verbose_name='Match Id'),
        ),
    ]
